#...............................................................................
#
#  This file is part of the Graco toolkit.
#
#  Graco is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/graco/license.txt
#
#...............................................................................

dist:      xenial
osx_image: xcode11.3
language:  cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
    - source ci/travis/set-env.sh
    - bash ci/travis/install-$TRAVIS_OS_NAME.sh
    - git clone --depth 1 http://github.com/vovkos/axl

script:
    - bash -e ci/travis/build.sh

notifications:
    webhooks:
        on_success: always
        on_failure: never
        on_error:   never
        on_cancel:  never

        urls:
            - http://jancy.org:5005/travis-ci
